// @ts-nocheck
// DO NOT MODIFY. This file is automatically generated by Studio.
export const firebaseConfig = {
  "projectId": "cantiereflow",
  "appId": "1:265686855947:web:1e5e77a709c85c09b1320e",
  "storageBucket": "cantiereflow.firebasestorage.app",
  "apiKey": "AIzaSyDRqdeNDYezPu3jIorVMdLsWhWT_kSdF9c",
  "authDomain": "cantiereflow.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "265686855947"
};
